-- AlterTable
ALTER TABLE "RequestLog" ALTER COLUMN "requestedAt" SET DEFAULT 0,
ALTER COLUMN "requestedAt" SET DATA TYPE BIGINT,
ALTER COLUMN "responsedAt" SET DEFAULT 0,
ALTER COLUMN "responsedAt" SET DATA TYPE BIGINT,
ALTER COLUMN "tookedFor" SET DEFAULT 0;
